# Generated by Django 4.0.2 on 2022-03-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
    ]
